const CONST = {
  DOMAIN: "http://80.87.110.6",
  ROLE: [
    "Mother",
    "Father",
    "Brother",
    "Sister",
    "Wife",
    "Familiar",
    "Svororkor",
    "Mother -in -law",
    "Father -in -law",
    "Dever",
    "Shurin",
    "Sillar",
    "Sword",
    "Ilust",
    "Son -in -law",
    "Daughter -in -law",
    "Matchmaker",
    "Fog",
    "Grandfather",
    "Cousin",
    "Grandson",
    "Granddaughter",
    "Nephew",
    "Niece",
    "Great-nephew",
    "A grandson of his niece",
    "Uncle",
    "Aunt",
    "Unified brother",
    "Unified sister",
    "A rash brother",
    "Reveal sister",
    "Step-brother",
    "Famous sister",
    "Second cousin",
    "Kum",
    "Kuma",
    "Stepmother",
    "Stepfather",
    "Stepson",
    "Stepdaughter",
    "Adoptive father",
    "The adoptive mother",
    "Foster-son",
    "Reception son -in -law",
    "Friend",
    "Comrade",
    "Girlfriend",
    "Lover",
    "Mistress",
    "Enemy",
    "Colleague",
    "Linge",
  ],
};
