"""add

Revision ID: 4ccdec66e5ef
Revises: cbd4c91e302e
Create Date: 2023-03-03 00:29:08.639560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccdec66e5ef'
down_revision = 'cbd4c91e302e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'payed')
    # ### end Alembic commands ###
