"""content

Revision ID: 7decf2b97b3f
Revises: 94b84eeb5135
Create Date: 2023-04-01 00:06:16.723467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7decf2b97b3f'
down_revision = '94b84eeb5135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isedit', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'content')
    op.drop_column('users', 'isedit')
    # ### end Alembic commands ###
