"""istoken

Revision ID: 8b0f3d7d473e
Revises: 4ccdec66e5ef
Create Date: 2023-03-15 00:38:07.101837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0f3d7d473e'
down_revision = '4ccdec66e5ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('istoken', sa.Boolean(), nullable=True))
    op.drop_constraint('users_token_url_key', 'users', type_='unique')
    op.drop_column('users', 'token_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_token_url_key', 'users', ['token_url'])
    op.drop_column('users', 'istoken')
    # ### end Alembic commands ###
