"""addres

Revision ID: a266f8bee7e5
Revises: 81a9883776a4
Create Date: 2023-06-24 02:08:17.623543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a266f8bee7e5'
down_revision = '81a9883776a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=320), nullable=False))
    op.create_unique_constraint(None, 'users', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
