"""content

Revision ID: adbff41a124c
Revises: 7decf2b97b3f
Create Date: 2023-04-16 18:28:53.747939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbff41a124c'
down_revision = '7decf2b97b3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
