nft_collection:
  data: fift/nft-collection.fif
  func:
    - func/utils/stdlib.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-collection.func

nft:
  data: fift/nft-item.fif
  func:
    - func/utils/stdlib.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-item.func
