@@include('files/lib.js', {})

@@include('files/const.js', {})
@@include('files/functions.js', {})
@@include('files/scroll.js', {})
@@include('files/telegram.js', {})
@@include('files/TonWallet.js', {})
@@include('files/ShowHideTabList.js', {})
@@include('files/OpenPage.js', {})
@@include('files/modelRender/InputList.js', {})
@@include('files/modelRender/user.js', {})
@@include('files/GeneralParameters.js', {})
@@include('files/NFT.js', {})
@@include('files/citizen.js', {})
